### ISSUE TITLE
code-caption插入不成功

### ISSUE THREAD

**Issue by bingofan** [Jamling/hexo-theme-nova#10]
代码高亮里面我的code-caption的div标签插入一直不成功，我想知道这段代码

``` javascript
 var ds = $(this).parent().prev(code_caption_selector).data();
    var texts = $(this).text().split('\n');
    if (ds.trim_indent === 'frontend') {
      console.log("trim indent in front-end");
      var tab = texts[0].match(/^\s{0,}/);
      if (tab) {
        var arr = [];
        texts.forEach(function(temp) {
          arr.push(temp.replace(tab, ''));
        });
        $(this).text(arr.join('\n'));
      }
    }
```

这个就是插入的代码吗？这个.data()函数会自动插入吗....

**Comment by Jamling** [comment]
不是的，`div.code-caption`是由[hexo-filter-highlight](https://github.com/Jamling/hexo-filter-highlight)插件生成的。data()函数用于取出`div.code-caption`的元数据，你插入`div.code-caption`不成功，难道是你没有安装这个[hexo-filter-highlight](https://github.com/Jamling/hexo-filter-highlight)这个插件？

**Comment by bingofan** [comment]
好吧,我才看到,我以为将hljs的js文件拷贝过来就可以了. ....还要安装这个,多谢了,我试试.

**Comment by Jamling** [comment]
[hexo-filter-highlight](https://github.com/Jamling/hexo-filter-highlight)插件是Nova主题的可选插件，安装后，才具备代码复制，代码高亮等高级功能。

**Comment by bingofan** [comment]
已经可以了,非常感谢~用在了我的博客上,的确非常好用!https://bingofan.github.io/

**Comment by Jamling** [comment]
@bingofan <g-emoji alias="smile" class="emoji mr-1" fallback-src="https://assets-cdn.github.com/images/icons/emoji/unicode/1f604.png"><img src="https://assets-cdn.github.com/images/icons/emoji/unicode/1f604.png" alt=":smile:" class="emoji" width="20" height="20"></g-emoji> 
我之前已经在你的博客看到效果了，所以close这条issue了。
