### ISSUE TITLE
请教一个关于 hexo 主题的 Travis CI 的问题

### ISSUE THREAD

**Issue by iblh** [Jamling/hexo-theme-nova#18]
我也在开发一个 hexo 主题，然后想用 Travis CI 测试一下代码的 build 状态。
但是不知道为什么一直是 build failing，主题代码也没有什么问题呀。不知道是不是和 .travis.yml 的配置有关？

> 尝试发了Gmail 邮件，似乎你的邮箱失效了，发送失败。

**Comment by Jamling** [comment]
你可以登录travis ci查看日志，看到底是哪里fail了。我的travis ci配置并没有真正运行测试用例。因为主题依赖于hexo和其它的一些插件。嫌麻烦。最小化配置请参考：[.travis.yml](https://github.com/Jamling/hexo-theme-nova/blob/master/.travis.yml)。

我的邮箱是gmail邮箱，如果你使用邮件客户端来发送，那应该是发送失败的。需要翻墙或使用网页版发送。你可以在我的博客找到我的其它联系方式。

欢迎对nova主题提供改进意见~

**Comment by iblh** [comment]
谢谢你的回复 😊

我登录了 Travis CI，但是看不到详细的报错消息 _(:з」∠)_
你没有用于测试的话，那 `README.md` 中的 `buildpassing` 是怎么弄出来的呢？

> 这个状态：![](https://camo.githubusercontent.com/01e9560c4a0bff20f19cefa061b6ae0fab9c64fb/68747470733a2f2f7472617669732d63692e6f72672f4a616d6c696e672f6865786f2d7468656d652d6e6f76612e7376673f6272616e63683d6d6173746572)

我是在 inbox.google.com 中发送的。我的邮箱是 [imviosey@gmail.com](mailto:imviosey@gmail.com)。
可以麻烦发送一封邮件给我吗？方便交流一下 :) 

> 不知道是不是我把你的邮箱地址输错了。

**Comment by Jamling** [comment]
邮件已发送，buildpassing是登录https://travis-ci.org/ ，然后点击 ![Build Status](https://travis-ci.org/Jamling/QuickAF.svg?branch=master) ，会弹出一个Status Image的对话框，选择markdown，复制代码即可。

PS：其实，你可以通过查看别人的README.md，然后修改用户名和项目名即可。

**Comment by iblh** [comment]
参考了你的 [.travis.yml](https://github.com/Jamling/hexo-theme-nova/blob/master/.travis.yml)
但是还是出错了：[![Build Status](https://travis-ci.org/viosey/hexo-theme-material.svg?branch=master)](https://travis-ci.org/viosey/hexo-theme-material)

下面是Job log
![travis-hexo-theme-test.png](https://ooo.0o0.ooo/2016/10/18/5805c2dce0214.png)

**Comment by iblh** [comment]
这个是[用于 Travis CI 的仓库](https://github.com/viosey/hexo-theme-material)
请麻烦你看看是否有哪里出错了呢？

**Comment by Jamling** [comment]
将package.json中的

```
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
```

删除，或者把`exit 1`改为`exit 0`

**Comment by iblh** [comment]
十分谢谢你！ 😁
问题解决啦。
