### ISSUE TITLE
toc not fixed sometimes

### ISSUE THREAD

**Issue by mygaochunming** [Jamling/hexo-theme-nova#2]
我很喜欢你的框架，但是打开具体文章时，右边的目录能否固定出现在右上角，不要随着滚动条消失啊。我试了几次，有时候点一下“语言”（不用进行选择），它就固定在右上角了，但不是每次都有效。
请教一下这个是可以设置的还是需要特殊处理？

**Comment by Jamling** [comment]
谢谢支持！
目录固定位置需要等文档加载完毕，因为引用的第三方脚本较多，有时会影响scrollspy的执行，我明天优化一下

**Comment by Jamling** [comment]
changed loading share_jiathis script to async
